# Generated by Django 3.1.1 on 2020-09-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='id',
        ),
        migrations.AddField(
            model_name='interest',
            name='interest_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='interests',
            field=models.ManyToManyField(default=0, related_name='user_interests', to='accounts.Interest'),
        ),
    ]
