# Generated by Django 3.1.1 on 2020-09-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer_clothes_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=64)),
                ('product', models.CharField(max_length=64)),
                ('product_model', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=64)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Offer_electronics_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=64)),
                ('product', models.CharField(max_length=64)),
                ('product_model', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=64)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Offer_hygiene_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=64)),
                ('product', models.CharField(max_length=64)),
                ('product_type', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=64)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Offer_sports_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=64)),
                ('product', models.CharField(max_length=64)),
                ('product_model', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=64)),
                ('description', models.TextField()),
            ],
        ),
    ]
